added starting of plans

diff --git a/cmd/kubectl-plugin/kubectl-maestro b/cmd/kubectl-plugin/kubectl-maestro
--- a/cmd/kubectl-plugin/kubectl-maestro
+++ b/cmd/kubectl-plugin/kubectl-maestro
@@ -335,7 +335,7 @@ then
     fi
 fi
 
-function createFunction {
+function createInstance {
     framework=$2
     shift 2
     while getopts ":n:v:p:" opt ; do
@@ -344,11 +344,9 @@ function createFunction {
                 c+=("$OPTARG")
                 ;;
                 n)
-                echo "name is: $OPTARG"
                 name=$OPTARG
                 ;;
                 v)
-                echo "version is: $OPTARG"
                 frameworkversion=$OPTARG
                 ;;                
                 \?)
@@ -393,7 +391,7 @@ EOF
 # create argument handling
 if [[ "$1" == "create" ]]
 then
-    createFunction "$@"
+    createInstance "$@"
     if [[ "$?" == "1" ]]
     then
         echo ""
@@ -401,7 +399,7 @@ then
         echo ""
         echo "Invalid create command."
         echo ""
-        echo "Syntax: kubectl maestro create -n <instanceName> -v <versionNumber> -p PARAM1=VALUE -p PARAM2=Value"
+        echo "Syntax: kubectl maestro create <framework> -n <instanceName> -v <versionNumber> -p PARAM1=VALUE -p PARAM2=Value"
         echo ""
         echo "Example: kubectl maestro create kafka -n kafka -v 2.11-2.4.0 -p KAFKA_ZOOKEEPER_URI:zk-zk-0.zk-hs:2181,zk-zk-1.zk-hs:2181,zk-zk-2.zk-hs:2181 -p KAFKA_ZOOKEEPER_PATH:\"/small\" -p BROKERS_COUNT:\"3\""
         exit 1
@@ -443,6 +441,66 @@ then
         echo "Example: kubectl maestro scale kafka --replicas=1"
         exit 1
         fi
+    fi
+    exit 0
+fi
+
+function startPlan {
+    shift 1
+    while getopts ":n:v:p:" opt ; do
+        case "$opt" in
+                p)   
+                planName=$OPTARG
+                ;;
+                n)
+                name=$OPTARG
+                ;;
+                v)
+                frameworkversion=$OPTARG
+                ;;                
+                \?)
+                echo "Invalid option: -$OPTARG" >&2
+                exit 1
+                ;;
+                :)
+                echo "Option -$OPTARG requires an argument." >&2
+                exit 1
+                ;;
+        esac
+    done
+    shift $((OPTIND-1))
+    cat <<EOF | kubectl apply -f -
+apiVersion: maestro.k8s.io/v1alpha1
+kind: PlanExecution
+metadata:
+    labels:
+        framework-version: $frameworkversion
+        instance: $name
+    name: $name
+spec:
+    instance:
+        kind: Instance
+        name: $name
+        namespace: default
+    planName: $planName
+EOF
+}
+
+# create argument handling
+if [[ "$1" == "start" ]]
+then
+    startPlan "$@"
+    if [[ "$?" == "1" ]]
+    then
+        echo ""
+        echo "Failed to create instance for framework $framework."
+        echo ""
+        echo "Invalid create command."
+        echo ""
+        echo "Syntax: kubectl maestro start -n <instanceName> -v <version> -p <planName>"
+        echo ""
+        echo "Example: kubectl maestro start -n demo -v flink-financial-demo -p upload"
+        exit 1
     fi
     exit 0
 fi
